### ISSUE TITLE
Issues with deploying to Heroku via Travis-CI

### ISSUE THREAD

**Issue by jscanning** [ionicsoft/vidon#23]
Getting the following error when running the build trough travis to deploy with Heroku:

```
No stash entries found.
API request failed.
Message: Invalid credentials provided.
Reference: 
failed to deploy
```
I think we may need to update the Heroku API key.
Otherwise may need to alter the encryption of the key.

**Comment by Wyvernix** [comment]
here's an issue that looks similar to ours: travis-ci/travis-ci#10018

**Comment by SRHarrison13** [comment]
Did this get fixed?
